version: '3'
services:
  kicker-rest:
    image: n52/kicker-rest:latest
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        JAR_FILE: "build/libs/kicker-rest-api-0.0.1-SNAPSHOT.jar"
    volumes: 
      - ./persistence/tmp:/tmp
    ports: 
      - 8080:8080
  kicker-config:
    image: n52/kicker-config:latest
    volumes: 
      - ./persistence/config/tmp:/tmp
    ports: 
      - 8888:8888
  kicker-registry:
    image: n52/kicker-registry:latest
    volumes: 
      - ./persistence/registry/tmp:/tmp
    ports: 
      - 8761:8761
