spring:
  application:
    name: kicker
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost/kickerdb
    username: postgres
    password: postgres
    #driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    root: INFO
    org.hibernate.engine.jdbc.env.internal: WARN
    org.springframework.security: DEBUG